version: '3.9'

services:
  # db:
  #   image: mysql/mysql-server:5.7.28
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: sample
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - 4306:3306
  #   volumes:
  #     - mysql-db:/var/lib/mysql
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/front/Dockerfile
  #   volumes:
  #     - ./front/app:/usr/src/app
  #   command: 'yarn dev'
  #   ports:
  #     - "8000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
     - "3000:8080"
    volumes:
      - ./src/:/go/src
    tty: true
